# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m_QhEHC0UwazA2s9QBeqIzpBsdLf0cN_

#Analysis Objectives
- Understand the characteristics of the food delivery dataset.

- Analyze and identify factors that affect delivery time and ratings.

- Analyze customer ordering and payment methods preferences.

- Evaluate restaurant and food item performance based on orders and rating.

- Investigate the relationship between delivery time, discounts, and customer ratings.

- Identify patterns that can help improve delivery efficiency and customer satisfaction.

#Questions to be answered:
1. What is the average delivery time for orders?

2. Which restaurants receive the highest number of orders?

3. What are the most ordered items?

4. Which payment method is used most frequently?

5. How do discounts affect customer ratings or order value?

6. Does delivery time affect customer ratings?

7. How do delivery times vary across different cities?


# The answers:
1. The average delivery time is 35.3 minutes. Most deliveries fall within the 31–40 minute ("Fair") category, indicating that orders are generally delivered within a reasonable time. 

2. Kebab House receives the highest number of orders, as indicated by the mode of the restaurant column.
 
3. Pizza is the most frequently ordered item, while Kebab is the least ordered. Between them there are(Pasta, Burger, Sushi). The grouped analysis also shows that Pizza is the most popular item in all three cities.

4. The Wallet payment method is used most frequently. However, the differences between Wallet, Card, and Cash are relatively small, indicating that customers use all three payment methods at similar rates. 

5. The correlation between discount and customer rating is −0.0015, which indicates a negligible negative linear relationship. This suggests that the discounts have no effect on the customers’ ratings. Discounts do, however, reduce the order value. A new feature, final_price, was created by subtracting the discount from the original price, allowing analysis of the actual amount paid by customers after discounts.

6. No. The correlation coefficient between delivery time and customer rating is negligible negative linear relationship. The scatter plot also shows no clear pattern, suggesting that customers give similar ratings regardless of delivery time. 

7. Average delivery times are very similar across the three cities. Cairo and Alex have identical average delivery times, and Giza has a slightly lower average time. Overall, the differences are small, suggesting that delivery performance is consistent across locations. 


#Dataset Understanding
- **Dataset dimensions**: 2050 x 12


---


- **Number or rows:** 2050 rows


---


- **Number of columns:** 12 columns


---


- **Column descriptions:**
 1. order_id: Unique identifier for each order.
 2. customer_id: Unique identifier for each customer.
 3. restaurant: Shows the restaurants names.
 4. city: Shows the cities names.
 5. order_date: Date of the order
 6. delivery_time_minutes: Time taken to deliver an order in minutes.
 7. item: What the ordered item was.
 8. quantity: How many of that item were ordered.
 9. price: How much the item was.
 10. discount: Amount deducted from the original price
 11. payment_method: Method used by the customer to pay for the order.
 12. rating: How was the customer's experience.


---


- **Data types:**
1. Numerical data: ['order_id', 'customer_id', 'delivery_time_minutes', 'quantity', 'price',
       'discount', 'rating']

2. Categorical data: ['restaurant', 'city', 'order_date', 'item', 'payment_method']


---


- **Initial observations:**
1.  The dataset has 2,050 delivery order records.

2.  Each row appears to represent a food delivery order.

3. The "order_date" column is currently stored as an object and needs to be fixed.

4. Some columns contain missing values, including `city`, `delivery_time_minutes`, and `rating`.

5. There are nearly 50 duplicated rows need to be dropped in order to end up with accurate analysis.

6. There are 24 outlier in the column `delivery_time_minutes`, and 10 outliers in the column `quantity`.

7. The dataset provides information that we can use to analyze delivery performance, customer ratings, restaurant sales, and payment method preferences.
"""

#Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#Reading the CSV file
df=pd.read_csv("Food_Delivery.csv")

#First five rows
df.head()

#Last five rows
df.tail()

#Peek on five random rows
df.sample(5)

#Dataset sahpe
df.shape

#Dataset number of columns
df.shape[1]

#Dataset names of columns
df.columns

#Dataset number of rows
df.shape[0]

#Dataset summary
df.info()

#Dataset statistical summary
df[["delivery_time_minutes", "quantity", "price", "discount", "rating"]].describe()

#Summary including categorical columns
df.describe(include="all")

#Data types in the dataset
df.dtypes

#Grouping numerical values
numerical_values=df.select_dtypes(include="number").columns
print(numerical_values)

#Grouping categorical values
categorical_values=df.select_dtypes(include="object").columns
print(categorical_values)

#Detecting inconsistent values in the column 'city'
df["city"].unique()

#Detecting inconsistent values in the column 'restaurant'
df["restaurant"].unique()

#Detecting inconsistent values in the column 'item'
df["item"].unique()

#Detecting inconsistent values in the column 'payment_method'
df["payment_method"].unique()

"""There are inconsistent values in the column `city`."""

#Detecting potential outliers
#1.Visually with box plot
df[["delivery_time_minutes", "quantity", "price", "discount", "rating"]].boxplot(figsize=(10, 10))
plt.show()

plt.boxplot(df["delivery_time_minutes"].dropna())
plt.title="Delivery Time (Minutes) - Outlier Detection"
plt.ylabel="Delivery Time (minutes)"
plt.show()

plt.boxplot(df["quantity"].dropna())
plt.title="Quantity outlier detection"
plt.show()

"""There are outliers in `delivery_time_ minutes` and `quantity`.





"""

#Detecting potential outliers
#2. Using IQR
#2.1.For "delivery_time_minutes"
q1=df["delivery_time_minutes"].quantile(0.25)
q2=df["delivery_time_minutes"].median()
q3=df["delivery_time_minutes"].quantile(0.75)
iqr=q3-q1

print(q1)
print(q3)

lower_bound_delivery=q1-1.5*(iqr)
upper_bound_delivery=q3+1.5*(iqr)

print(lower_bound_delivery)
print(upper_bound_delivery)

outliers_deliver_time=df[(df["delivery_time_minutes"]>upper_bound_delivery)| (df["delivery_time_minutes"]<lower_bound_delivery)]
print(outliers_deliver_time["delivery_time_minutes"].values)

print(outliers_deliver_time["delivery_time_minutes"].count())

#2.2.For "quantity"
q1=df["quantity"].quantile(0.25)
q2=df["quantity"].median()
q3=df["quantity"].quantile(0.75)
iqr=q3-q1

lower_bound_quantity=q1-1.5*(iqr)
upper_bound_quantity=q3+1.5*(iqr)

outliers_quantity=df[(df["quantity"]>upper_bound_quantity)| (df["quantity"]<lower_bound_quantity)]
print(outliers_quantity["quantity"].values)

print(outliers_quantity["quantity"].count())

#2.3.For "price"
q1=df["price"].quantile(0.25)
q2=df["price"].median()
q3=df["price"].quantile(0.75)
iqr=q3-q1

lower_bound_price=q1-1.5*(iqr)
upper_bound_price=q3+1.5*(iqr)

outliers_price=df[(df["price"]>upper_bound_price)| (df["price"]<lower_bound_price)]
print(outliers_price["price"].values)

#2.4.For "discount"
q1=df["discount"].quantile(0.25)
q2=df["discount"].median()
q3=df["discount"].quantile(0.75)
iqr=q3-q1

lower_bound_dicount=q1-1.5*(iqr)
upper_bound_discount=q3+1.5*(iqr)

outliers_price=df[(df["discount"]>upper_bound_discount)| (df["discount"]<lower_bound_dicount)]
print(outliers_price["discount"].values)

#2.4.For "rating"
q1=df["rating"].quantile(0.25)
q2=df["rating"].median()
q3=df["rating"].quantile(0.75)
iqr=q3-q1

lower_bound_rating=q1-1.5*(iqr)
upper_bound_rating=q3+1.5*(iqr)

outliers_price=df[(df["rating"]>upper_bound_rating)| (df["rating"]<lower_bound_rating)]
print(outliers_price["rating"].values)

"""There are outliers in `delivery_time_ minutes` and `quantity`.
And this shows that the IQR Rule gave the same result as the Box Plot
"""

#Replacing the outliers with the median
condition = (
    (df["delivery_time_minutes"] > upper_bound_delivery) |
    (df["delivery_time_minutes"] < lower_bound_delivery)
)
median = df["delivery_time_minutes"].median()
df.loc[condition, "delivery_time_minutes"] = median

condition = (
    (df["quantity"] > upper_bound_delivery) |
    (df["quantity"] < lower_bound_delivery)
)
median = df["quantity"].median()
df.loc[condition, "quantity"] = median

#Detecting duplicates
df.duplicated().sum()

duplicate_ids = df[df["order_id"].duplicated(keep=False)]
duplicate_ids.sort_values("order_id")

# Remove duplicate rows after verifying they are exact duplicate records
df=df.drop_duplicates()

# Making sure they are drpped
df.duplicated().sum()

#fixing incossitency
df["city"]=df["city"].str.lower().str.strip()

#Making sure all the values in 'city' are conssistant
df["city"].unique()

#Detecting missing values
df.isnull().sum()

#Filling the missing values in "city" with the Mode
df["city"]=df["city"].fillna(df["city"].mode()[0])

#Filling the missing values in "delivery_time_minutes" with the median
df["delivery_time_minutes"]=df["delivery_time_minutes"].fillna(df["delivery_time_minutes"].median())

#Filling the missing values in "rating" with the mean
df["rating"]=df["rating"].fillna(df["rating"].mean())

#Veryfing there are no longer missing values
df.isnull().sum()

#Fixing data type for the order_date column
df["order_date"] = pd.to_datetime(df["order_date"])

#Descriptive statistics
df[["delivery_time_minutes", "quantity", "price", "discount", "rating"]].describe()

"""The describe() function results is now accurate after removing the duplicates, filling the missing values with the (mean, median, or mode) and replacing all the outliers with the median."""

#Getting the median for all the numerical columns
df[["delivery_time_minutes", "quantity", "price", "discount", "rating"]].median()

#Getting the range for all the numerical columns
min=df["delivery_time_minutes"].min()
max= df["delivery_time_minutes"].max()
range=max-min
print(range)

min=df["quantity"].min()
max= df["quantity"].max()
range=max-min
print(range)

min=df["price"].min()
max= df["price"].max()
range=max-min
print(range)

min=df["discount"].min()
max= df["discount"].max()
range=max-min
print(range)

min=df["rating"].min()
max= df["rating"].max()
range=max-min
print(range)

# Histograms
df[["delivery_time_minutes", "quantity", "price", "discount", "rating"]].hist(figsize=(8, 8))
plt.show()

#Categorical summary and observations
#1. Grouping the categorical columns
categorical_values=df.select_dtypes(include="object").columns
print(categorical_values)

#2. How many categorical columns there are
print(len(categorical_values))

#3. The most frequent value in each category(column)
df[["restaurant", "city", "item", "payment_method"]].mode()

"""Above we can see the result of the mode() function, that tells that the most famous restaurant is 'Kebab House', most of the orders are from 'cairo', 'Pizza'is the most ordered item, and most of the people love to pay with their 'Wallet'."""

#4. Visuals
df['item'].value_counts().plot(kind="bar", title="Ordered items")

"""The distribution of ordered food items is relatively balanced across all categories. Pizza is the most frequently ordered item, while Kebab is the least. The differences in order frequencies are relatively small, indicating that customers have fairly diverse food preferences."""

df['payment_method'].value_counts().plot(kind="pie", autopct="%1.1f%%", title="Payment methods")

"""The differences between the payment methods are subtle, indicating that customers use all payment methods at relatively similar rates."""

df['city'].value_counts().plot(kind="pie", autopct="%1.1f%%", title="Cities")

"""The pie chart shows that Cairo has the largest proportion of customer orders (52.9%), followed by Alexandria (32.0%), while Giza has the smallest share (15.1%). This indicates that the majority of orders originate from Cairo, suggesting that customer demand is concentrated there."""

#Discovering some patterns
#1. Numerical vs Numerical
print(df['delivery_time_minutes'].corr(df['rating']))

"""There is a negligible negative linear relationship between `rating` and `delivery_time_minutes`. This indicates that there is no meaningful linear relationship between the two variables."""

print(df['discount'].corr(df['rating']))
"""There is a negligible negative linear relationship between `rating` and `discount`. This indicates that there is no meaningful linear relationship between the two variables."""


df.plot(kind="scatter", x='delivery_time_minutes', y="rating", xlabel="Delivery time in minutes", ylabel="Rating")

"""The scatter plot shows no clear relationship between delivery time and customer ratings. Ratings from 1 to 5 are observed across nearly all delivery times, indicating that customers give similar ratings regardless of how long the delivery takes."""

#2. Numerical vs Categorical
plt.bar(df['city'], df['delivery_time_minutes'])
plt.title="Correlation between the city and the delivery time in minutes"
plt.ylabel="Delivery time"
plt.show()

"""The bar chart shows that the average delivery time is very similar in Cairo and Alexandria, while Giza has a slightly lower average delivery time. Overall, the differences between the three cities are small, suggesting that delivery performance is fairly consistent across locations."""

df.groupby(df['restaurant'])["rating"].mean().plot(kind="bar",  title="Restaurants Ratings", xlabel="Restaurant", ylabel="Rate")

"""The bar chart shows that Kebab House has the highest average customer rating, while Pasta Point has the lowest average rating among the five restaurants. However, the differences in average ratings are relatively small, with all restaurants receiving ratings close to 3 out of 5
This suggests that customer satisfaction is fairly similar across all restaurants.
"""

#3. Categorical vs Categorical
pd.crosstab(df["city"], df["item"]).plot(kind="bar", title="Ordered items in each city")

"""The grouped bar chart compares the number of orders for each food item across the three cities. It confirms the earlier finding that Cairo has the highest number of orders, followed by Alex, while Giza has the fewest orders.
Across all three cities, Pizza is the most frequently to be the ordered item, showing that it is the most popular  item regardless of the city. In contrast, Kebab and Sushi generally receive fewer orders.
The total number of orders differs between cities but the ordering patterns are similar.
 Cairo has more orders for every item, which may indicate a larger customer base or higher demand in Cairo rather than a preference for a specific item.
"""

#Delivery performance groups
df["delivery_groups"]=pd.cut(df["delivery_time_minutes"], bins=[0, 30.0, 40.0, 68.0], labels=["fast", "fair", "slow"])

df["delivery_groups"].value_counts()

"""Most deliveries are completed within the Fair delivery time range, while Slow deliveries are the least common. This suggests that the delivery service generally efficient, with only the smallest proportion of orders taking an unusually long time."""

#Creating meaningful features
df["rating_groups"]=pd.cut(df['rating'], bins=[0, 1, 2, 3, 4, 5], labels=["poor", "fair", "good", "very good", "excellent"])
print(df['rating_groups'].sample(5))

df["rating_groups"].value_counts()

"""Most customer ratings fall within the Good category, suggesting that the overall customer experience is positive."""

#Cassifying orders based om prices
df["price_groups"]=pd.cut(df['price'], bins=[0, 80, 180, 300 ], labels=["low", "medium", "high"])
print(df["price_groups"].sample(5))

df["price_groups"].value_counts()

"""The order prices were categorized into three groups: Low, Medium, and High. The results show that High-priced orders are the most common (919 orders), and
Low-priced orders are the least common (255 orders). This distribution indicates that the restaurants sell a large proportion of the orders from higher-priced items, which may contribute positively to overall revenue.
"""

#Getting the final price after disount
df["final_price"]=df["price"]-df["discount"]
print(df[["price","discount", "final_price"]].sample(5))

"""The column `final_price`, was created by subtracting the discount from the original price. This derived metric represents the actual amount paid by the customer and can be used to analyze customer spending, compare revenue across restaurants, or evaluate the impact of discounts on sales.

##Added features:

1. **Delivery Groups**: Categorized delivery times into (Fast, Fair, and Slow) to examine delivery performance.

2. **Rating Groups**: Grouped customer ratings into (Poor, Fair, Good, Very good or Excellent) for easier comparison.

3. **Order Value**: Classified orders as (Low, Medium, or High) value based on the prices.

4. **Final Price**: Calculated the amount paid after discounts using (price - discount) for easier future calculations
"""

#Creating visualizations
#1. Line chart
monthly_orders=df.groupby(df["order_date"].dt.month_name())["order_id"].count()
monthly_orders=monthly_orders.reindex(["January", "February", "March"])
monthly_orders.plot(kind="line", marker="o", title="Orders per month over the year", xlabel="Time(Month)", ylabel="Number of orders", )

"""The line chart shows that January had the highest number of orders, followed by February, while March had the lowest number of orders. This shows a downward trend in customer orders over the three months."""

#2. Bar chart
df["rating_groups"].value_counts().plot(kind="bar", title="Rating Frequency", xlabel="Rating Groups", ylabel="Number of Orders")

"""The bar chart shows that biggest number of customer ratings fall within the Good category. This indicates that the majority of the customers' experiences are generally positive."""

#3. Histogram
df["final_price"].plot(kind="hist", bins=20, title="The Final Price", xlabel="The items' final prices", ylabel="Frequency")

"""The distribution of final prices is fairly balanced, with most orders falling within the middle price ranges. Very low and very high final prices are less common, indicating that customers typically make moderately priced purchases after discounts."""
'''
#Achieved objectives:
1. Data Preparation and Cleaning
Removed duplicate records after verifying they were true duplicates.
Handled missing values in the city, rating, and delivery_time_minutes columns.
Standardized inconsistent categorical values.
Detected and treated outliers.
Converted order_date to the correct datetime data type.
_________________________________________________________________________
2. Feature Engineering
Created new features to improve the analysis:
final_price
rating_groups
delivery_groups
price_groups
_________________________________________________________________________
3. Exploratory Data Analysis
Numerical Variables
Examined the distribution, range, and spread of numerical features.
Identified outliers and overall data patterns.
Categorical Variables
Analyzed category frequencies and dominant categories.
Data Visualization
Used multiple visualization techniques, including:
Bar charts
Histograms
Box plots
Scatter plots
Line charts
Cross-tabulation charts
_________________________________________________________________________
4. Delivery Time Analysis
Calculated the average delivery time.
Classified deliveries into Fast, Fair, and Slow groups.
Compared delivery times across different cities.
Analyzed the overall distribution of delivery times.
_________________________________________________________________________
5. Restaurant Performance Analysis
Identified restaurants with the highest number of orders.
Compared restaurants based on average customer ratings.
Determined the highest-rated and lowest-rated restaurants.
_________________________________________________________________________
6. Customer Ordering Behavior
Identified the most frequently ordered food items.
Compared food popularity across different cities.
Categorized orders into price groups.
Used the final_price feature to analyze actual customer spending.
_________________________________________________________________________
7. Relationship Analysis
Investigated the relationship between delivery time and customer ratings.
Investigated the relationship between discounts and customer ratings.
Compared delivery performance across cities.
Explored relationships between numerical and categorical variables using correlation analysis and visualizations.
_________________________________________________________________________
Business Insights
Identified that most deliveries are completed within a reasonable time.
Found that delivery time has almost no effect on customer ratings.
Found that discounts have almost no effect on customer ratings.
Determined the most popular restaurants, food items, and payment methods.
'''

'''
# Business Recommendations
1. Improve delivery speed by increasing the proportion of fast deliveries.
* Supporting Evidence: Most orders fall into the Fair (31–40 minutes) delivery category, while Slow deliveries are relatively uncommon.
* Expected Business Impact: Faster deliveries can improve the customer experience and encourage repeat orders.
2. Introduce marketing campaigns to increase customer demand.
* Supporting Evidence: The number of orders declined from January to March.
* Expected Business Impact: Promotions, loyalty programs, and targeted advertising can help increase order volume and customer retention.
3. Promote the most popular food items.
* Supporting Evidence: Pizza is the most frequently ordered item across all cities.
* Expected Business Impact: Featuring popular items in promotions can increase sales and overall revenue.
4. Improve the quality and service of lower-rated restaurants.
* Supporting Evidence: Pasta Point has the lowest average customer rating, while Kebab House has the highest.
* Expected Business Impact: Addressing customer concerns can improve satisfaction, increase ratings, and encourage repeat business.
5. Continue supporting multiple payment methods.
* Supporting Evidence: Customers use Wallet, Card, and Cash at similar frequencies.
* Expected Business Impact: Offering several payment options maintains customer convenience and accommodates different preferences.
6. Focus on service quality rather than increasing discounts.
* Supporting Evidence: The correlation between discount and customer rating is −0.0015, indicating virtually no relationship.
* Expected Business Impact: Investing in food quality and delivery service is more likely to improve customer satisfaction than offering larger discounts.
7. Maintain consistent delivery performance across all cities.
* Supporting Evidence: Average delivery times are very similar in Cairo, Alexandria, and Giza.
* Expected Business Impact: Consistent service quality across locations helps build customer trust and strengthens the brand's reputation.
8. Monitor delivery performance regularly.
* Supporting Evidence: Delivery time showed almost no relationship with customer ratings, but maintaining efficient delivery operations remains important for service reliability.
* Expected Business Impact: Continuous monitoring helps identify operational issues early and supports long-term service improvement.

'''